# Use official Tomcat image with Java 17
FROM tomcat:10.1-jdk17-temurin

# Remove the default ROOT app
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy your JSP project files into Tomcat’s webapps directory
COPY . /usr/local/tomcat/webapps/ROOT

# Expose Tomcat default port
EXPOSE 8080

# Start Tomcat when container runs
CMD ["catalina.sh", "run"]
